name: nhost_flutter_graphql
description: >
  Provides GraphQL clients to your Flutter application, automatically configured
  to work with Nhost
version: 3.0.0-dev.18
homepage: https://nhost.io
repository: https://github.com/nhost/nhost-dart/tree/main/packages/nhost_flutter_graphql
issue_tracker: https://github.com/nhost/nhost-dart/issues

environment:
  sdk: '>=2.14.0 <3.0.0'
  flutter: '>=2.8.0'

dependencies:
  flutter:
    sdk: flutter
  graphql_flutter: ^5.1.0
  logging: ^1.1.0

  #Nhost_dart
  nhost_flutter_auth: ^3.0.0-dev.15

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: any
  mockito: ^5.3.2
