name: nhost_flutter_graphql
description: >
  Provides GraphQL clients to your Flutter application, automatically configured
  to work with Nhost
version: 1.0.3
homepage: https://nhost.io
repository: https://github.com/nhost/nhost-dart/tree/main/packages/nhost_flutter_graphql
issue_tracker: https://github.com/nhost/nhost-dart/issues

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  graphql_flutter: ^5.0.0-nullsafety.1

  # Nhost packages
  nhost_sdk: ^1.0.3
  nhost_flutter_auth: ^1.0.3
  nhost_graphql_adapter: ^1.0.6
dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.0.2
  pedantic: ^1.11.0
