name: nhost_graphql_adapter
version: 4.0.9
description: Easily connect to your Nhost.io GraphQL backend using the graphql package.
homepage: https://nhost.io
repository: https://github.com/nhost/nhost-dart/tree/main/packages/nhost_graphql_adapter
issue_tracker: https://github.com/nhost/nhost-dart/issues

environment:
  sdk: ">=2.14.0 <4.0.0"

dependencies:
  graphql: ^5.2.3
  http: ^1.1.0
  meta: ^1.7.0

  #Nhost_dart
  nhost_gql_links: ^4.0.10
  nhost_sdk: ^5.7.0
dev_dependencies:
  async: ^2.10.0
  lints: ^2.0.0
  mockito: 5.4.4
  nock: ^1.2.1
  stream_channel: ^2.1.1
  test: ^1.22.0
  web_socket_channel: ^2.2.0
