name: nhost_graphql_adapter
version: 3.0.0-dev.12
description: Easily connect to your Nhost.io GraphQL backend using the graphql package.
homepage: https://nhost.io
repository: https://github.com/nhost/nhost-dart/tree/main/packages/nhost_graphql_adapter
issue_tracker: https://github.com/nhost/nhost-dart/issues

environment:
  sdk: '>=2.14.0 <3.0.0'

dependencies:
  graphql: ^5.1.1
  http: ^0.13.5
  meta: ^1.7.0

  #Nhost_dart
  nhost_dart: ^1.0.0-dev.4
  nhost_gql_links: ^3.0.0-dev.12
dev_dependencies:
  async: ^2.10.0
  lints: any
  mockito: ^5.3.2
  nock: ^1.2.1
  stream_channel: ^2.1.1
  test: ^1.22.0
  web_socket_channel: ^2.2.0
