name: nhost_graphql_adapter
version: 1.0.10
description: Easily connect to your Nhost GraphQL backend.
homepage: https://nhost.io
repository: https://github.com/nhost/nhost-dart/tree/main/packages/nhost_graphql_adapter
issue_tracker: https://github.com/nhost/nhost-dart/issues

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  graphql: ^5.0.0
  http: ^0.13.1
  meta: ^1.3.0

  # Nhost packages
  nhost_sdk: ^2.0.0
  nhost_gql_links: ^1.1.2
dev_dependencies:
  async: ^2.5.0
  mockito: ^5.0.2
  nock: ^1.2.0
  pedantic: ^1.11.0
  stream_channel: ^2.1.0
  test: ^1.16.8
  web_socket_channel: ^2.0.0
