name: nhost_graphql_adapter
version: 2.0.1
description: Easily connect to your Nhost.io GraphQL backend using the graphql package.
homepage: https://nhost.io
repository: https://github.com/nhost/nhost-dart/tree/main/packages/nhost_graphql_adapter
issue_tracker: https://github.com/nhost/nhost-dart/issues

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  graphql: ^5.0.0
  http: ^0.13.1
  meta: ^1.3.0

  # Nhost packages
  nhost_sdk: ^3.0.1
  nhost_gql_links: ^2.0.1
dev_dependencies:
  async: ^2.5.0
  lints: ^1.0.0
  mockito: ^5.0.2
  nock: 1.1.3
  stream_channel: ^2.1.0
  test: ^1.18.0
  web_socket_channel: ^2.0.0
