# This is used to establish tool dependencies, and is never published.
name: nhost_dart
publish_to: none
homepage: https://nhost.io
repository: https://github.com/nhost/nhost-dart

environment:
  sdk: ">=2.14.0 <=3.2.5"

dev_dependencies:
  dotenv: ^4.2.0
  melos: ^4.0.0
  path: ^1.8.3
