name: nhost_flutter_auth
description: >
  Provides Nhost authentication state to your Flutter app, making it easy to set
  up protected resources, and react to sign ins and sign outs.
version: 3.0.0-dev.14
homepage: https://nhost.io
repository: https://github.com/nhost/nhost-dart/tree/main/packages/nhost_flutter_auth
issue_tracker: https://github.com/nhost/nhost-dart/issues

environment:
  sdk: '>=2.14.0 <3.0.0'
  flutter: '>=2.8.0'

dependencies:
  flutter:
    sdk: flutter
  #Nhost_dart
  nhost_dart: ^1.0.0-dev.7
dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: any
  mockito: ^5.3.2
