name: nhost_flutter_auth
description: >
  Provides Nhost authentication state to your Flutter app, making it easy to set
  up protected resources, and react to logins and logouts.
version: 1.0.9
homepage: https://nhost.io
repository: https://github.com/nhost/nhost-dart/tree/main/packages/nhost_flutter_auth
issue_tracker: https://github.com/nhost/nhost-dart/issues

environment:
  sdk: '>=2.14.0 <3.0.0'
  flutter: ">=1.22.4"

dependencies:
  flutter:
    sdk: flutter

  # Nhost packages
  nhost_sdk: ^2.0.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^1.0.0
  mockito: ^5.0.0
