name: nhost_graphql_example
description: Demonstrates usage of the nhost_graphql package
publish_to: none
version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  graphql: ^5.1.3

  # Nhost packages
  nhost_dart: ^1.0.0-dev.7

dev_dependencies:
  lints: any
