name: nhost_graphql_example
description: Demonstrates usage of the nhost_graphql package
publish_to: none
version: 2.0.1

environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  graphql: ^5.1.3

  # Nhost packages
  nhost_dart: ^2.2.0
dev_dependencies:
  lints: ^2.0.0
