name: nhost_auth_dart
description: Nhost Dart Auth Service SDK
version: 1.0.0-dev.3
homepage: https://nhost.io
repository: https://github.com/nhost/nhost-dart/tree/main/packages/nhost_sdk
issue_tracker: https://github.com/nhost/nhost-dart/issues

environment:
  sdk: '>=2.14.0 <3.0.0'

dependencies:
  http_parser: ^4.0.1
  http: ^0.13.4
  logging: ^1.1.0
  meta: ^1.7.0
  #Nhost_sdk
  nhost_sdk: ^4.0.0-dev.10

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
