name: nhost_dart
description: Nhost Dart SDK
version: 1.0.1
homepage: https://nhost.io
repository: https://github.com/nhost/nhost-dart/tree/main/packages/nhost_sdk
issue_tracker: https://github.com/nhost/nhost-dart/issues

environment:
  sdk: ">=2.14.9 <3.0.0"

dependencies:
  http_parser: ^4.0.1
  http: ^1.1.0
  logging: ^1.1.0
  meta: ^1.7.0
  path: ^1.8.0

  #NHOST Package
  nhost_sdk: ^4.0.0
  nhost_storage_dart: ^1.0.1
  nhost_auth_dart: ^1.0.0
  nhost_functions_dart: ^1.0.0
  nhost_graphql_adapter: ^3.0.0
dev_dependencies:
  betamax: ^2.0.0
  fake_async: ^1.3.1
  graphql: ^5.1.3
  lints: any
  mockito: ^5.3.2
  nock: ^1.2.1
  otp: "3.1.3"
  stack_trace: ^1.11.0
  test_api: ^0.4.16
  test: ^1.22.0
  gql: ^0.14.0
  gql_exec: ^0.4.3
  nhost_gql_links: ^3.0.0
  async: ^2.10.0
  stream_channel: ^2.1.1
  web_socket_channel: ^2.2.0
