name: nhost_dart
description: Nhost Dart SDK
version: 2.1.0
homepage: https://nhost.io
repository: https://github.com/nhost/nhost-dart/tree/main/packages/nhost_sdk
issue_tracker: https://github.com/nhost/nhost-dart/issues

environment:
  sdk: ">=2.14.9 <4.0.0"

dependencies:
  http_parser: ^4.0.1
  http: ^1.1.0
  logging: ^1.1.0
  meta: ^1.7.0
  path: ^1.8.0

  #NHOST Package
  nhost_sdk: ^5.7.0
  nhost_storage_dart: ^2.1.0
  nhost_auth_dart: ^2.6.0
  nhost_functions_dart: ^2.0.9
  nhost_graphql_adapter: ^4.0.9
dev_dependencies:
  fake_async: ^1.3.1
  graphql: ^5.2.3
  lints: ^2.0.0
  mockito: 5.4.4
  nock: ^1.2.1
  otp: ^3.2.0
  stack_trace: ^1.11.0
  test_api: ^0.7.7
  test: ^1.22.0
  gql: ^1.0.0
  gql_exec: ^1.0.0
  nhost_gql_links: ^4.0.10
  async: ^2.10.0
  stream_channel: ^2.1.1
  web_socket_channel: ^3.0.0
  uuid: ^4.0.0
