name: nhost_sdk
description: Nhost authentication and file storage/retrieval APIs for the Dart language.
version: 5.7.0
homepage: https://nhost.io
repository: https://github.com/nhost/nhost-dart/tree/main/packages/nhost_sdk
issue_tracker: https://github.com/nhost/nhost-dart/issues

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  http_parser: ^4.0.1
  http: ^1.1.0
  jwt_decoder: ^2.0.1
  logging: ^1.1.0
  meta: ^1.7.0
  path: ^1.8.0

dev_dependencies:
  fake_async: ^1.3.1
  graphql: ^5.2.3
  lints: ^2.0.0
  mockito: 5.4.4
  nock: ^1.2.1
  otp: ^3.2.0
  stack_trace: ^1.11.0
  test_api: ^0.7.7
  test: ^1.22.0
