name: nhost_sdk
version: 1.0.3
description: Nhost authentication and file storage/retrieval APIs for the Dart language.
homepage: https://nhost.io
repository: https://github.com/nhost/nhost-dart/tree/main/packages/nhost_sdk
issue_tracker: https://github.com/nhost/nhost-dart/issues

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  http: ^0.13.0
  http_parser: ^4.0.0
  jwt_decoder: ^2.0.0
  meta: ^1.0.0
  path: ^1.0.0
  pedantic: ^1.8.0

dev_dependencies:
  betamax: ^1.0.0
  fake_async: ^1.0.0
  graphql: ^5.0.0-nullsafety.1
  nock: ^1.0.0
  otp: '>=3.0.0-nullsafety.0 <4.0.0'
  stack_trace: ^1.0.0
  test_api: ^0.2.19
  test: ^1.6.0

  # Nhost packages
  nhost_graphql_adapter: ^1.0.4