name: nhost_functions_dart
description: Nhost Dart Functions Service SDK
version: 1.0.0
homepage: https://nhost.io
repository: https://github.com/nhost/nhost-dart/tree/main/packages/nhost_sdk
issue_tracker: https://github.com/nhost/nhost-dart/issues

environment:
  sdk: ">=2.14.9 <=3.1.5"

dependencies:
  http_parser: ^4.0.1
  http: ^1.1.0
  logging: ^1.1.0
  #Nhost_sdk
  nhost_sdk: ^4.0.0
dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
