name: nhost_flutter_auth_example
publish_to: none
environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  app_links: ^2.0.0
  provider: '>=4.0.0'
  shared_preferences: ^2.0.0
  url_launcher: ^6.0.0

  # Nhost packages
  nhost_flutter_auth:
    path: ../

flutter:
  uses-material-design: true
