name: nhost_flutter_auth_example
description: Nhost Flutter auth package example
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 2.0.0

environment:
  sdk: '>=2.18.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  app_links: ^3.3.0
  provider: '>=6.0.4'
  shared_preferences: ^2.0.15
  url_launcher: ^6.1.7

  # Nhost packages
  nhost_flutter_auth:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
