name: nhost_gql_links
version: 2.0.0-beta.2
description: Constructs GraphQL links for use with graphql and ferry packages
homepage: https://nhost.io
repository: https://github.com/nhost/nhost-dart/tree/main/packages/nhost_gql_links
issue_tracker: https://github.com/nhost/nhost-dart/issues

environment:
  sdk: '>=2.14.0 <3.0.0'

dependencies:
  gql_exec: ^0.3.0
  gql_http_link: ^0.4.0
  gql_link: ^0.4.0
  gql_websocket_link: ^0.3.1
  gql: ^0.13.0
  http: ^0.13.1
  logging: ^1.0.1
  meta: ^1.3.0
  web_socket_channel: ^2.0.0

  # Nhost packages
  nhost_sdk: ^3.0.0-beta.2
dev_dependencies:
  async: ^2.5.0
  fake_async: ^1.2.0
  lints: ^1.0.0
  mockito: ^5.0.2
  nock: ^1.2.0
  stream_channel: ^2.1.0
  test: ^1.18.0
