name: nhost_gql_links
version: 4.0.3
description: Constructs GraphQL links for use with graphql and ferry packages
homepage: https://nhost.io
repository: https://github.com/nhost/nhost-dart/tree/main/packages/nhost_gql_links
issue_tracker: https://github.com/nhost/nhost-dart/issues

environment:
  sdk: ">=2.14.0 <4.0.0"

dependencies:
  gql_exec: ^1.0.0
  gql_http_link: ^1.0.1
  gql_link: ^1.0.0
  gql_websocket_link: ^2.0.1
  gql: ^1.0.0
  http: ^1.1.0
  logging: ^1.1.0
  meta: ^1.7.0
  web_socket_channel: ^2.2.0

  #Nhost_dart
  nhost_sdk: ^5.1.1
dev_dependencies:
  async: ^2.10.0
  fake_async: ^1.3.1
  lints: any
  mockito: ^5.3.2
  nock: ^1.2.1
  stream_channel: ^2.1.1
  test: ^1.22.0
