name: nhost_flutter_graphql_example
publish_to: 'none'
environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  graphql: ^4.0.0

  # Nhost packages
  nhost_flutter_graphql:
    path: ../

flutter:
  uses-material-design: true
